// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TranVanTuyen760.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20211215063117_TVT0760")]
    partial class TVT0760
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TranVanTuyen760.Models.TVT0760", b =>
                {
                    b.Property<string>("TVTId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TVTGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TVTName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TVTId");

                    b.ToTable("TVT0760");
                });

            modelBuilder.Entity("TranVanTuyen760.Models.UniversityTVT760", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityId");

                    b.ToTable("UniversityTVT760");
                });
#pragma warning restore 612, 618
        }
    }
}
